(import std.Exceptions:*)
(import std.Testing)

(let invert (fun (x)
    (if (= x 0)
        (throw "cannot divide by zero")
        (return (/ 1 x)))))

(test:suite exceptions {
    (try (invert 0)
        (fun (inverted) (test:expect false))
        (fun (err) (test:expect (= err "cannot divide by zero"))))})
